name: Semantic Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

  workflow_dispatch:

concurrency:
  group: Semantic Release

jobs:
  release:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEM_VER }}
          fetch-depth: 0

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.SEM_VER }}
