# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
Default Branch: main

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
assignees:
  - imAsparky

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs:

# set a global prefix for PRs
# default: empty
pr_prefix: "fix(pyup): "

# allow to close stale PRs
# default: True
close_prs: False

requirements:
  - "docs/requirements.txt"
  - "config/requirements/base.txt"
  - "config/requirements/local.txt"
  - "config/requirements/test.txt"
  - "{{cookiecutter.git_project_name}}/config/requirements/base.txt"
  - "{{cookiecutter.git_project_name}}/config/requirements/local.txt"
  - "{{cookiecutter.git_project_name}}/config/requirements/production.txt"
  - "{{cookiecutter.git_project_name}}/config/requirements/staging.txt"
  - "{{cookiecutter.git_project_name}}/config/requirements/test.txt"
  - "{{cookiecutter.git_project_name}}/docs/requirements.txt"
