default_language_version:
  python: python3.10
default_stages: [commit]
fail_fast: true
exclude: ".conf.py|migrations|.git|.tox"
# exclude: ".conf.py|^tests/|migrations|.git|.tox"
ci:
  autofix_commit_msg: |
    chore(pre-commit): Auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: "chore(pre-commit): Weekly pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Section commented out issue-252. target-version=4.0 broken
  # - repo: https://github.com/adamchainz/django-upgrade
  #   rev: 1.2.0
  #   hooks:
  #     - id: django-upgrade
  #       args: [--target-version, "4.0"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args: ["--django"]
      - id: requirements-txt-fixer
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args: [-l  88]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
        exclude: tests/


  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]
        args: [
              --ignore=W503,
              --max-line-length=105,
             ]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-directive-colons
      # - id: rst-backticks
      - id: rst-inline-touching-normal
      - id: python-no-log-warn
      - id: python-no-eval
      - id: text-unicode-replacement-char
