name: Test Contributions

on:
  pull_request:
    branches: [main]

  # push:
  #     branches: [main]

  workflow_dispatch:

jobs:
  tests:
    strategy:
    fail-fast: false
    matrix:
      os:
        - macos-latest
        - ubuntu-latest
        - windows-latest

    name: Set up ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Test with tox
        run: tox
